### ISSUE TITLE
mp4 파일생성이 되지만 interval이 잘 나눠지지 않고, jpg가 빈 바이트로 들어오는 현상

### ISSUE THREAD

**Issue by graykode** [AlphaKHU/AlphaKHU#1]
@YeongBean https://github.com/AlphaKHU/AlphaKHU/commit/b3f87e2561a10e28598f9cdd32f3f7a749375faa

실행결과
- youtube url : https://www.youtube.com/watch?v=KkQCjTtzbsI, (3분 정도 동영상)
- 시간간격 : 10

mp4 파일은 생성되나 대략 3분/10초 = 18개 정도 이미지가 생겨야하나
데이터가 빈 이미지가 10000개 넘개 생성됨

![image](https://user-images.githubusercontent.com/10525011/57964374-7a32ef80-796f-11e9-8d54-6dc8b87ed220.png)

**Comment by graykode** [comment]
```python
while(True):
   success,image = vidcap.read()
   if not success:
      break
```
를 `if not success`로 다시 수정했더니 frame은 생성되지 않으며

파일 삭제시 다음과 같은 오류 발생

```
Traceback (most recent call last):
  File "C:\Users\nlkey\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\nlkey\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\nlkey\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\nlkey\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\nlkey\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nlkey\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nlkey\OneDrive\바탕 화면\AlphaKHU\main.py", line 49, in youtube
    os.remove('./youtube/frame/' + yt.title + ".mp4")
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: './youtube/frame/불리하던 흑, 중앙 패싸움으로 역전-2019 한국여자바둑리그 2R 1G 서울 부광약품:부안 곰소소금.mp4'
```

**Comment by RoastedPerilla** [comment]
![frame progress](https://user-images.githubusercontent.com/37439238/57969089-99507200-79ad-11e9-84eb-bf4ed8ebf034.jpg)

웹으로 확인되었습니다.
